#!/usr/bin/env python3
# Generates src/helpers/ui/UiIcons.h (XBM arrays) + tools/icons_preview.png
# from the open-iconic icon font (MIT). Run: python3 tools/gen_icons.py
#
# Icons are real designed glyphs from open-iconic (https://github.com/iconic/open-iconic),
# rendered via Pillow and thresholded to 1-bit XBM. Font: tools/iconfont/open-iconic.ttf.
from PIL import Image, ImageDraw, ImageFont
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TTF = os.path.join(ROOT, "tools/iconfont/open-iconic.ttf")

# enum name -> open-iconic codepoint (from font/css/open-iconic.css)
ICONS16 = [("ICON_BELL",0xe01d),("ICON_ENVELOPE",0xe05c),("ICON_QUESTION",0xe0b0),
           ("ICON_HOME",0xe078),("ICON_PERSON",0xe0a5),("ICON_GROUP",0xe0a4),
           ("ICON_SEND",0xe0bb),("ICON_GEAR",0xe041),("ICON_LOCK",0xe08a),
           ("ICON_CHECK",0xe033),("ICON_CROSS",0xe0db),("ICON_HEART",0xe077)]
ICONS8  = [("ICON_DOT",0xe094),("ICON_CHEVRON_UP",0xe037),("ICON_CHEVRON_DOWN",0xe034),
           ("ICON_CHEVRON_LEFT",0xe035),("ICON_CHEVRON_RIGHT",0xe036),
           ("ICON_CHECK_SM",0xe033),("ICON_BTN",0xe094),
           ("ICON_ENVELOPE_SM",0xe05c),("ICON_SEND_SM",0xe0bb),("ICON_GEAR_SM",0xe041),
           ("ICON_PERSON_SM",0xe0a5),("ICON_GROUP_SM",0xe0a4)]

def render_glyph(cp, target, thresh=120):
    # Render the glyph directly at the target pixel size (FreeType hints strokes to the
    # pixel grid — far crisper at 16/8px than supersample+downscale), centered, threshold.
    f = ImageFont.truetype(TTF, target)
    img = Image.new("L", (target, target), 0)
    d = ImageDraw.Draw(img)
    ch = chr(cp)
    bbox = d.textbbox((0, 0), ch, font=f)
    gw, gh = bbox[2]-bbox[0], bbox[3]-bbox[1]
    d.text(((target-gw)//2 - bbox[0], (target-gh)//2 - bbox[1]), ch, fill=255, font=f)
    return img.point(lambda v: 255 if v >= thresh else 0, mode="1")

def xbm_bytes(img1):                          # MSB-first (Adafruit GFX drawBitmap), row padded to byte
    w, h = img1.size; px = img1.load(); out = []
    bpr = (w+7)//8
    for y in range(h):
        for b in range(bpr):
            v = 0
            for bit in range(8):
                x = b*8+bit
                if x < w and px[x, y]: v |= (0x80 >> bit)   # leftmost pixel = bit 7
            out.append(v)
    return out

def emit(f, name, img1):
    f.write(f"static const uint8_t {name}_bits[] = {{\n  ")
    f.write(", ".join(f"0x{b:02x}" for b in xbm_bytes(img1)))
    f.write("\n};\n")

def main():
    out = os.path.join(ROOT, "src/helpers/ui/UiIcons.h")
    enum_ids = [n for n,_ in ICONS16] + [n for n,_ in ICONS8]
    previews = []
    with open(out, "w") as f:
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write("// GENERATED by tools/gen_icons.py from open-iconic (MIT) — do not edit by hand.\n\n")
        f.write("enum UiIconId {\n  " + ", ".join(enum_ids) + ", UI_ICON_COUNT\n};\n")
        f.write("const uint8_t* uiIcon(UiIconId id, int* w, int* h);\n\n")
        for name, cp in ICONS16:
            b = render_glyph(cp, 16); emit(f, name, b); previews.append((name, b))
        for name, cp in ICONS8:
            b = render_glyph(cp, 8); emit(f, name, b); previews.append((name, b))
    cols = 6; cell = 8*8 + 10
    sh = Image.new("L", (cols*cell, ((len(previews)+cols-1)//cols)*cell), 48)
    for i, (name, b) in enumerate(previews):
        z = b.convert("L").resize((b.size[0]*8, b.size[1]*8))
        sh.paste(z, ((i % cols)*cell + 4, (i//cols)*cell + 4))
    sh.save(os.path.join(ROOT, "tools/icons_preview.png"))
    print("wrote", out, "and tools/icons_preview.png")

if __name__ == "__main__":
    main()
